### ISSUE TITLE
Use case of your SVIM software

### ISSUE THREAD

**Issue by anandksrao** [eldariont/svim#11]
Hi David,

Thank you for making your SVIM software available to the research community.

I am starting on a new project of trying to discover SV in **assembled genomes** of same plant species.

It appears to me, from details at https://github.com/eldariont/svim and https://github.com/eldariont/svim/wiki that the inputs have to **reads**, rather than fully assembled genomes. Or can I use entire genome. In which case, I will align various genomes to one of them as a reference?

I mean, if I want to discover SVs across 20 individuals, then I'd choose fasta assembly of 1 individual my reference, and fasta assemblies of rest 19 as queries? Is this possible in theory? And is this possible in practice?

Or can I break each of my 19 non-reference genomes into let's say 50kB fake fasta contiguous reads?

Could you please advise me? Thanks, in advance.

Sincerely,
Anand

**Comment by wdecoster** [comment]
For assembly based SV calling other tools exist, e.g. https://github.com/lh3/CHM-eval/blob/master/dip-call/README.md or Assemblytics.

**Comment by eldariont** [comment]
Hi Anand,

thanks for your message and the interesting question.

You are right that SVIM was designed for detecting SVs from aligned long reads, not entire chromosomes/contigs. But theoretically it could work for whole genomes as well if you provide a SAM/BAM file with the aligned contigs (e.g. aligned to one of the other genomes) as input.

One question that will arise in practice though is which alignment tool to use to align the contigs. You need an aligner that can split the long contigs into multiple split alignments. That is particularly necessary for detecting inversions and duplications. You could try minimap2 with a command like `minimap2 -ax asm5 asm1.fa asm2.fa > aln.sam`. But you'd probably have to play around with the parameters until it might work. I have never tried something like this with SVIM so you might come upon problems that I don't see yet.

As Wouter pointed out there are several tools specifically designed for detecting SVs from genome-genome alignments, such as Assemblytics (https://doi.org/10.1093/bioinformatics/btw369) or paftools (https://github.com/lh3/minimap2/blob/master/misc/README.md#asmvar).

Another approach could be what you mention - breaking the assemblies into fake long reads. If you try this, however, you should generate reads in an overlapping fashion (i.e. sampling reads randomly from your assembly instead of just splitting the assembly into non-overlapping pieces).

Thanks again and if you have results with any of these options or more questions feel free to share.
David

**Comment by eldariont** [comment]
I will close this for now.
