### ISSUE TITLE
error with /bin/sh and set -o pipefail

### ISSUE THREAD

**Issue by curtisjamison** [eldariont/svim#13]
The python run command uses /bin/sh by default. Not all Linux installations support "set -o pipefail". Consider updating the run commands with the executable flag set:

run(" ".join(command), shell=True, check=True, executable='/bin/bash')

**Comment by eldariont** [comment]
Hi and thanks for reporting this issue!
Do I understand correctly that "set -o pipefail" is a feature of bash and not necessarily other sh implementations which is why it's safer to use /bin/bash? That is what I have just learnt by quickly reading up on it.
In that case, I will adopt your proposed change with one of my next commits.

Cheers
David
