### ISSUE TITLE
Error at stage of GENOTYPE

### ISSUE THREAD

**Issue by Edison2021** [eldariont/svim#15]
Hi David 
I mapped the long reads to reference genome using minimap2, and then used the SIVM to call SV, The command line i used is "svim alignment $dir $bam ". At stage of GENOTYPE, i got a error message that was "RGBA values should be within 0-1 range".  Any suggestions? Thanks
Edison

**Comment by eldariont** [comment]
Hi Edison,

thanks for reporting this issue.
Could you please give me some more information, such as the exact version of SVIM you are using and the complete log that SVIM outputs which will also contain the line in the source code that caused the error?

Cheers
David

**Comment by eldariont** [comment]
Hi Edison,

I think I found the source of the error you observed. In its latest version 1.1.0 SVIM generates a scatter plot of genotypes. To avoid clutter from many SVs, SVIM chooses the alpha (transparency) value for the points dynamically and there was a bug in there that caused alpha to be >1 for a low number (<100) of called SVs. This is now fixed in the latest commit and I hope that it will also fix your problem.

Please reinstall svim over pip with `pip3 install svim --upgrade` or wait a few hours until the fixed version 1.1.1 has made it to conda. This issue is now closed but don't hesitate to reopen it if your problem persists.

Thanks a lot again for making me aware of this bug.
David
