### ISSUE TITLE
Sequences of insertion

### ISSUE THREAD

**Issue by Edison2021** [eldariont/svim#16]
Hi David
I would like to explore the features of insertion predicted by SVIM, Is there any option to extract these insertion sequences or the reads with insertion? 

Thanks
Edison

**Comment by eldariont** [comment]
Hi Edison,
first of all, sorry for the long delay. I was out of office for two weeks.

Let me answer your question with the help of an example: When we have an insertion spanned by four reads the inserted sequence might look different in each read. Therefore, we would need to do a multiple sequence alignment between all four insertion sequences to produce a consensus sequence that we can then output. Unfortunately, SVIM does not perform such a multiple sequence alignment so that we do not get a consensus sequence. Of course, we could select and output one insertion sequence randomly but that would not be a very elegant solution.

I am planning to implement the output of deletion and inversion sequences in the VCF soon because that does not require a multiple sequence alignment. If it would help you I could also output the list of insertion sequences for each insertion. You could analyze those or generate your own consensus sequence from them. Would that be of help?

Cheers
David

**Comment by Edison2021** [comment]
Hi David
Outputting the list of insertion sequences would be very helpful for my project!!
Thanks
Edison

**Comment by eldariont** [comment]
Hi Edison,

I just commited a change to svim that adds an option (`--insertion_sequences`) to output the insertion sequences in the VCF. Just call svim with:
`svim alignment --insertion_sequences <WORKDIR> <BAM> <REF>`

To extract the insertion sequences you could i.e. use the following command which prints the ID and SEQS of each insertion:
`bcftools query -i 'INFO/SVTYPE=="INS"' -f '%ID\t%INFO/SEQS\n' final_results.vcf`

I also added two other options, that enable the output of names of supporting reads (`--read_names`) and the output of sequence alleles instead of symbolic alleles (`--sequence_alleles`).

Best
David

**Comment by Edison2021** [comment]
Thanks!  David!
