### ISSUE TITLE
SV types in output VCF

### ISSUE THREAD

**Issue by shimbalama** [eldariont/svim#28]
Hi,

In your WIKI you describe five different SVTYPEs: DEL, INV, DUP:TANDEM, DUP:INT, and INS:NOVEL.

I get all the above plus:

]chr19:107955]N
N[chr19:107969[
N[chr19:111124[
N[chr6:69267[
]chr1:278176]N

all SVTYPE=BND

What are these? Rubbish to filter out?

Liam

**Comment by eldariont** [comment]
Hi Liam,

sorry for the delay. I was out of the office for a week.
The records you mention are breakends reported in the format that is described in the VCF specification. Have a look at http://samtools.github.io/hts-specs/VCFv4.2.pdf and particularly at section 5.4.

Best
David

**Comment by zihhuafang** [comment]
Hi David,

I actually have same question. 
I think what Liam meant to say is that svim doesn't report BND type of SV according to your wiki explanation.
Did I misunderstand because I did find svim report translocations?
I check a couple of translocations reported by svim by visualising the read alignment with ribbon and they seem to be true.

Best wishes,
Zih-Hua

**Comment by eldariont** [comment]
Hi Zih-Hua, hi Liam,

yes, you are right. I should mention breakends (BNDs) in the wiki to avoid confusion. I did not mention breakends before because they do not represent one SV type but rather a mix of different things: Some represent translocations, many of them are caused by spurious split-read alignments (often close to telomeres and centromeres) while others could be part of more complex rearrangements. The best definition I have for BNDs is that they represent one or more reads that connect two distant genomic loci on the same or different chromosomes.

So every translocation will be detected as a BND variant by SVIM but not every BND variant is a translocation. I hope that makes it a bit clearer what they are :) Thanks for making me aware that I should be more explicit about this in the wiki.

Cheers
David
