### ISSUE TITLE
FORMAT 'CN' is not defined in the header

### ISSUE THREAD

**Issue by d2389758** [eldariont/svim#29]
Hi David,

Thanks for developing SVIM.
I am filtering SV called by SVIM and ran into this issue with the variants.vcf.
There are DUP_TAN variants with GT:CN:DP:AD, but CN was not defined in the header.
I checked wiki and did not find any information about CN.
I am not sure what to do with these variants since these are pass variants.

Would love to get your insights about it.
Thanks!
Best wishes,
Zih-Hua

**Comment by eldariont** [comment]
Hi Zih-Hua,

thanks for your question and for spotting this issue. I recently added the CN tag in response to a user's request (see #24) and obviously forgot to define it in the header. This should be fixed now with the most recent commit.

The CN tag stores the copy number of a tandem duplication. For instance, a copy number of 3 would mean that the region between POS and END was duplicated two times so that there are now 3 tandem copies.

Let me know if you have further questions.
Cheers
David

**Comment by d2389758** [comment]
Hi David,

Thanks for the reply.
I use svim=1.3.0=py_0 (installed via bioconda), and encountered this issue.
Should I use git instead to have the most recent commit?

**Comment by eldariont** [comment]
Hi Zih-Hua,

yes, I updated only the github repository while conda is still on the previous version (1.3.0). I update conda regularly but not after every change because most changes, including this one, are not huge.

With the last commit I only added one line to the header that defines the CN tag. If you want to install this latest version you need to install svim from the github repo with

```
git clone https://github.com/eldariont/svim.git
cd svim
pip install .
```

Best
David
