### ISSUE TITLE
Improved Documentation

### ISSUE THREAD

**Issue by CharlesARoy** [eldariont/svim#49]
Thanks so much for developing this tool and making it accessible to the research community!

As I was getting started with SVIM I noticed that in the [example analysis](https://github.com/eldariont/svim/wiki/3.-Evaluation-on-HG002-with-GiaB-draft-truth-set) you use options like `--interspersed_duplications_as_insertions` and `--max_sv_size 1000000`. I've tried to find a place where all options are listed (e.g. with svim --help) along with a description of what they do, but I haven't been able to find one. Does such documentation exist?

Thanks for your help!

**Comment by eldariont** [comment]
Hi Charles,

first of all, I'm very sorry for my long reply time.
To list all the options of SVIM along with their description you can use `svim alignment --help` or `svim reads --help` depending on which mode of SVIM you use. `svim --help` only gives you a general overview of the two modes so that's why it didn't return what you where looking for.

I hope this does not come too late and is of help. Let me know if you have any other questions.
Best
David

**Comment by CharlesARoy** [comment]
Thanks very much, that's exactly what I was looking for!
