### ISSUE TITLE
Accept coordinate sorted alignments

### ISSUE THREAD

**Issue by armintoepfer** [eldariont/svim#5]
Hi!

All alignment visualizers rely on a coordinate sorted alignment, yet your tool requires me to resort again, which can be annoying when dealing with >100GB BAM files. Why do you need a special sorting? If you need info about all supplementary alignments for each read, make use of the `SA` tag.

Armin

**Comment by eldariont** [comment]
Hi Armin,

thanks for the feedback. As you have already guessed, sorting the BAM file by queryname allows me to quickly retrieve all supplementary alignments of a read. Infering the information I need from the `SA` tag should not be much of a problem, so I hope to accept coordinate-sorted alignment files soon.

Cheers
David

**Comment by eldariont** [comment]
Hi @armintoepfer,

I have implemented accepting coordinate-sorted BAMs on the branch "satag". But as it turns out the SA tag (e.g. in minimap2) contains only a shortened version of the CIGAR strings of the supplementary alignments. That means I cannot locate deletions and insertions precisely from the SA tag alone. Therefore, I would need to retrieve the entire alignment record of each supplementary alignment which would slow down SVIM considerably.

Am I overlooking something here or is that the only way? If it is, I will probably offer users both options: giving query-sorted or coordinate-sorted BAM files.

**Comment by eldariont** [comment]
With  4524f8b, SVIM now supports both queryname-sorted and coordinate-sorted SAM/BAM files. queryname sorting is still recommended because it enables SVIM to access the primary and all supplementary alignments of each read at the same time.
When input is coordinate-sorted, SVIM uses the SA tag to gather information about the supplementary alignments. As described before, the problem is that the CIGAR string in the SA tag is shortened (see https://github.com/lh3/minimap2/pull/287) which can lead to slightly less accurate results. For the benchmark described in the wiki it led to a tiny decrease in F1 from 93.18% to 93.16%.
