### ISSUE TITLE
Understand the output?

### ISSUE THREAD

**Issue by wenbinmei** [eldariont/svim#52]
Hi,
It seemst he score in column QUAL is the same as SUPPORT(##INFO=<ID=SUPPORT,Number=1,Type=Integer,Description="Number of reads supporting this variant">), also the number is the same as alternative allele count. All these three numbers are from 0 to 100, It doesn't make sense?

Also SUPPORT is number of reads supporting this variant, i have much high depth called using other tools but still below 100 in SVIM. Also why QUAL score is the same as number of reads support alt alleles? 

Could you help me understand this? Thanks.

All the best,
wenbin

**Comment by eldariont** [comment]
Hi Wenbin,

thanks for your questions. You are mentioning the following three values in the VCF file produced by SVIM:
- The SUPPORT field contains the number of reads supporting the variant.
- The AD field contains the read depth for each allele. The depth of the alternative allele is, by definition, identical to the number of reads supporting the variant (i.e. the SUPPORT field).
- The QUAL field contains the variant score which is related but not identical to the SUPPORT. See [here](https://github.com/eldariont/svim/wiki/2.-Interpreting-the-output#how-is-the-score-defined-that-each-variant-call-receives) for a detailed explanation of the score.

Does this answer some of your questions?
Why does it not make sense to you that the numbers are in the range between 0 and 100? Is your read depth above 100 so that you expected SVIM to return values above 100?

Best
David
